from typing import Any, Generic, TypeVar

T = TypeVar("T")

class Value(Generic[T]): ...
class Text(Value[str]): ...
class Number(Value[int | float]): ...
class Bool(Value[bool]): ...
class File(Value[object]): ...
class Image(Value[object]): ...
class List(Value[list[T]]): ...

def shortcut(*, name: str, color: str | int | None = None, glyph: str | int | None = None): ...
def ask_for_text(prompt: str, /, *, default: str | None = None) -> Text: ...
def choose_from_menu(prompt: str, options: list[str], /) -> Text: ...
def show_result(value: Text | Number | Bool | str | int | float | bool, /) -> None: ...
def get_files(*, prompt: str | None = None) -> List[File]: ...
def resize_image(image: Image | File, /, *, width: int, height: int | None = None) -> Image: ...
def save_file(value: File | Image, /, *, ask_where: bool = True) -> File: ...
def raw_action(action_id: str, /, **params: Any) -> Value[Any]: ...
