from typing import Any, Callable, Generic, Literal, TypeAlias, TypeVar, overload

T = TypeVar("T")
F = TypeVar("F", bound=Callable[..., Any])

class Value(Generic[T]): ...
class Text(Value[str]): ...
class Number(Value[int | float]): ...
class Bool(Value[bool]): ...
class File(Value[object]): ...
class Image(Value[object]): ...
class Dictionary(Value[dict[str, Any]]):
    def __getitem__(self, key: str | Value[Any], /) -> Value[Any]: ...
class List(Value[list[T]]):
    def __getitem__(self, index: int, /) -> T: ...

Input: TypeAlias = Value[Any] | str | int | float | bool | None | list[Any] | dict[str, Any]
NumberLike: TypeAlias = Number | int | float
BoolLike: TypeAlias = Bool | bool
ArrayLike: TypeAlias = List[Any] | list[Any]
DictLike: TypeAlias = Dictionary | dict[str, Any]

@overload
def shortcut(fn: F, /) -> F: ...
@overload
def shortcut(*, name: str | None = None, color: str | int | None = None, glyph: str | int | None = None,
    input_types: list[str] | tuple[str, ...] | None = None) -> Callable[[F], F]: ...
def ask_for_datetime(prompt: Input, /, *, default: Input | None = None) -> Value[Any]: ...
def ask_for_text(prompt: str, /, *, default: str | None = None) -> Text: ...
def choose_from_menu(prompt: str, options: list[str], /) -> Text: ...
def show_result(value: Text | Number | Bool | str | int | float | bool, /) -> None: ...
def get_files(*, prompt: str | None = None) -> List[File]: ...
def preferred_language() -> Text: ...
def resize_image(image: Image | File, /, *, width: int, height: int | None = None) -> Image: ...
def save_file(value: File | Image, /, *, ask_where: bool = True) -> File: ...
def raw_action(action_id: str, /, **params: Any) -> Value[Any]: ...
def shortcut_input() -> Value[Any]: ...
def unix_timestamp(date: Input, /) -> Number: ...
AbcSortOrderValue: TypeAlias = Literal['A to Z', 'Z to A']
AirdropReceivingStatesValue: TypeAlias = Literal['No One', 'Contacts Only', 'Everyone']
ArchiveFormatValue: TypeAlias = Literal['.zip', '.tar.gz', '.tar.bz2', '.tar.xz', '.tar', '.gz', '.cpio', '.iso']
AudioFormatsValue: TypeAlias = Literal['M4A', 'AIFF']
AudioQualityValue: TypeAlias = Literal['Normal', 'Very High']
AudioSpeedsValue: TypeAlias = Literal['0.5X', 'Normal', '2X']
AudioStartValue: TypeAlias = Literal['On Tap', 'Immediately']
BackgroundSoundValue: TypeAlias = Literal['BalancedNoise', 'BrightNoise', 'DarkNoise', 'Ocean', 'Rain', 'Stream']
CalculationOperationValue: TypeAlias = Literal['x^2', 'х^3', 'x^у', 'e^x', '10^x', 'In(x)', 'log(x)', '√x', '∛x', 'x!', 'sin(x)', 'cos(X)', 'tan(x)', 'abs(x)']
CameraOrientationValue: TypeAlias = Literal['Front', 'Back']
CellularDetailValue: TypeAlias = Literal['Carrier Name', 'Radio Technology', 'Country Code', 'Is Roaming Abroad', 'Number of Signal Bars']
ColorSpaceValue: TypeAlias = Literal['RGB', 'Gray']
ContactDetailValue: TypeAlias = Literal['First Name', 'Middle Name', 'Last Name', 'Birthday', 'Prefix', 'Suffix', 'Nickname', 'Phonetic First Name', 'Phonetic Last Name', 'Phonetic Middle Name', 'Company', 'Job Title', 'Department', 'File Extension', 'Creation Date', 'File Path', 'Last Modified Date', 'Name', 'Random']
ConvertImageFormatsValue: TypeAlias = Literal['TIFF', 'GIF', 'PNG', 'BMP', 'PDF', 'HEIF']
CountTypeValue: TypeAlias = Literal['Items', 'Characters', 'Words', 'Sentences', 'Lines']
CropImagePositionValue: TypeAlias = Literal['Center', 'Top Left', 'Top Right', 'Bottom Left', 'Bottom Right', 'Custom']
CustomImageOverlayPositionValue: TypeAlias = Literal['Center', 'Top Left', 'Top Right', 'Bottom Left', 'Bottom Right', 'Custom']
DateAdjustOperationValue: TypeAlias = Literal['Add', 'Subtract', 'Get Start of Minute', 'Get Start of Hour', 'Get Start of Day', 'Get Start of Week', 'Get Start of Month', 'Get Start of Year']
DateFormatsValue: TypeAlias = Literal['None', 'Short', 'Medium', 'Long', 'Relative', 'RFC 2822', 'ISO 8601', 'Custom']
DateUnitValue: TypeAlias = Literal['sec', 'min', 'hr', 'days', 'weeks', 'months', 'yr']
DeviceDetailValue: TypeAlias = Literal['Device Name', 'Device Hostname', 'Device Model', 'Device Is Watch', 'System Version', 'Screen Width', 'Screen Height', 'Current Volume', 'Current Brightness', 'Current Appearance']
DeviceUsageTypeValue: TypeAlias = Literal['all', 'app', 'website']
EditEventDetailValue: TypeAlias = Literal['Start Date', 'End Date', 'Is All Day', 'Location', 'Duration', 'My Status', 'Attendees', 'URL', 'Title', 'Notes', 'Attachments']
EncodeVideoSizesValue: TypeAlias = Literal['640×480', '960×540', '1280×720', '1920×1080', '3840×2160', 'HEVC 1920×1080', 'HEVC 3840x2160', 'ProRes 422']
EncodeVideoSpeedsValue: TypeAlias = Literal['0.5X', 'Normal', '2X']
EventDetailValue: TypeAlias = Literal['Start Date', 'End Date', 'Is All Day', 'Calendar', 'Location', 'Has Alarms', 'Duration', 'Is Canceled', 'My Status', 'Organizer', 'Organizer Is Me', 'Attendees', 'Number of Attendees', 'URL', 'Title', 'Notes', 'Attachments', 'File Size', 'File Extension', 'Creation Date', 'File Path', 'Last Modified Date', 'Name']
EventOccurrenceModeValue: TypeAlias = Literal['Next Occurrence', 'Specified Year']
FacetimeCallTypeValue: TypeAlias = Literal['Video', 'Audio']
FileDetailValue: TypeAlias = Literal['File Size', 'File Extension', 'Creation Date', 'File Path', 'Last Modified Date', 'Name']
FileSizeFormatValue: TypeAlias = Literal['Closest Unit', 'Bytes', 'Kilobytes', 'Megabytes', 'Gigabytes', 'Terabytes', 'Petabytes', 'Exabytes', 'Zettabytes', 'Yottabytes']
FlipImageDirectionValue: TypeAlias = Literal['Horizontal', 'Vertical']
FocusUntilValue: TypeAlias = Literal['Turned Off', 'Time', 'I Leave', 'Event Ends']
GenerativeResultTypeValue: TypeAlias = Literal['Text', 'Number', 'Date', 'Boolean', 'List', 'Dictionary']
HashTypeValue: TypeAlias = Literal['MD5', 'SHA1', 'SHA256', 'SHA512']
HolidayValue: TypeAlias = Literal["April Fools' Day", 'Ash Wednesday', 'Christmas Day', 'Christmas Eve', 'Cinco de Mayo', 'Columbus Day', 'Day of the Dead', 'Daylight Saving Time', 'Daylight Saving Time End', 'Diwali', 'Earth Day', 'Easter Sunday', 'Eid al-Adha', 'Eid al-Fitr', 'Election Day', "Father's Day", 'First Night of Ramadan', 'Flag Day', 'Good Friday', 'Groundhog Day', 'Halloween', 'Holi', 'Inauguration Day', 'Independence Day', "Indigenous Peoples' Day", 'Juneteenth', 'Martin Luther King Jr. Day', 'Memorial Day', "Mother's Day", "New Year's Day", "New Year's Eve", 'Palm Sunday', "Presidents' Day", "St. Patrick's Day", 'Tax Day', 'Thanksgiving', "Valentine's Day", 'Veterans Day', "Workers' Day"]
HolidayYearValue: TypeAlias = Literal['2023', '2024', '2025', '2026', '2027']
HttpMethodValue: TypeAlias = Literal['POST', 'PUT', 'PATCH', 'DELETE']
ImageCombineModeValue: TypeAlias = Literal['Vertically', 'In a Grid']
ImageDetailValue: TypeAlias = Literal['Album', 'Width', 'Height', 'Date Taken', 'Media Type', 'Photo Type', 'Is a Screenshot', 'Is a Screen Recording', 'Location', 'Duration', 'Frame Rate', 'Orientation', 'Camera Make', 'Camera Model', 'Metadata Dictionary', 'Is Favorite', 'File Size', 'File Extension', 'Creation Date', 'File Path', 'Last Modified Date', 'Name']
IpTypesValue: TypeAlias = Literal['IPv4', 'IPv6']
LanguageValue: TypeAlias = Literal['ar_AE', 'zh_CN', 'zh_TW', 'nl_NL', 'en_GB', 'en_US', 'fr_FR', 'de_DE', 'id_ID', 'it_IT', 'jp_JP', 'ko_KR', 'pl_PL', 'pt_BR', 'ru_RU', 'es_ES', 'th_TH', 'tr_TR', 'vn_VN']
LlmModelValue: TypeAlias = Literal['Private Cloud Compute', 'Apple Intelligence on Device', 'ChatGPT']
LocationDetailValue: TypeAlias = Literal['Name', 'URL', 'Label', 'Phone Number', 'Region', 'ZIP Code', 'State', 'City', 'Street', 'Altitude', 'Longitude', 'Latitude']
MaskImageTypeValue: TypeAlias = Literal['Rounded Rectangle', 'Ellipse', 'Icon']
MusicDetailValue: TypeAlias = Literal['Title', 'Album', 'Artist', 'Album Artist', 'Genre', 'Composer', 'Date Added', 'Media Kind', 'Duration', 'Play Count', 'Track Number', 'Disc Number', 'Album Artwork', 'Is Explicit', 'Lyrics', 'Release Date', 'Comments', 'Is Cloud Item', 'Skip Count', 'Last Played Date', 'Rating', 'File Path', 'Name']
PdfMergeBehaviorsValue: TypeAlias = Literal['Append', 'Shuffle']
PodcastDetailValue: TypeAlias = Literal['Feed URL', 'Genre', 'Episode Count', 'Artist', 'Store ID', 'Store URL', 'Artwork', 'Artwork URL', 'Name']
QrCodeErrorCorrectionValue: TypeAlias = Literal['Low', 'Medium', 'Quartile', 'High']
RecordingStartValue: TypeAlias = Literal['On Tap', 'Immediately']
RepeatModeValue: TypeAlias = Literal['None', 'One', 'All']
RoundingValue: TypeAlias = Literal['Ones Place', 'Tens Place', 'Hundreds Place', 'Thousands', 'Ten Thousands', 'Hundred Thousands', 'Millions']
ScreenshotSelectionValue: TypeAlias = Literal['Window', 'Custom']
SearchEngineValue: TypeAlias = Literal['Amazon', 'Bing', 'DuckDuckGo', 'eBay', 'Google', 'Reddit', 'Twitter', 'Yahoo!', 'YouTube']
SeekBehaviorValue: TypeAlias = Literal['To Time', 'Forward By', 'Backward By']
ShazamDetailValue: TypeAlias = Literal['Apple Music ID', 'Artist', 'Title', 'Is Explicit', 'Lyrics Snippet', 'Lyric Snippet Synced', 'Artwork', 'Video URL', 'Shazam URL', 'Apple Music URL', 'Name']
ShortcutDetailValue: TypeAlias = Literal['Folder', 'Icon', 'Action Count', 'File Size', 'File Extension Creation Date', 'File Path', 'Last Modified Date', 'Name']
ShuffleModeValue: TypeAlias = Literal['Off', 'Songs']
SoundRecognitionOperationsValue: TypeAlias = Literal['pause', 'activate', 'toggle']
SshScriptAuthTypeValue: TypeAlias = Literal['Password', 'SSH Key']
StatisticOperationsValue: TypeAlias = Literal['Average', 'Minimum', 'Maximum', 'Sum', 'Median', 'Mode', 'Range', 'Standard Deviation']
StopListeningTriggerValue: TypeAlias = Literal['After Pause', 'After Short Pause', 'On Tap']
StorageUnitValue: TypeAlias = Literal['bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'Y']
TextSizesValue: TypeAlias = Literal['Accessibility Extra Extra Extra Large', 'Accessibility Extra Extra Large', 'Accessibility Extra Large', 'Accessibility Large', 'Accessibility Medium', 'Extra Extra Extra Large', 'Extra Extra Large', 'Extra Large', 'Default', 'Medium', 'Small', 'Extra Small']
TextToneValue: TypeAlias = Literal['friendly', 'professional', 'concise']
TimeDurationValue: TypeAlias = Literal['hr', 'min', 'sec']
TimeFormatsValue: TypeAlias = Literal['None', 'Short', 'Medium', 'Long', 'Relative']
UrlDetailValue: TypeAlias = Literal['Scheme', 'User', 'Password', 'Host', 'Port', 'Path', 'Query', 'Fragment']
UsageDurationValue: TypeAlias = Literal['today', 'yesterday', 'lastWeek', 'thisWeek', 'thisMonth', 'thisYear', 'specifiedDay', 'inBetween']
VideoQualityValue: TypeAlias = Literal['Low', 'Medium', 'High']
WeatherDetailValue: TypeAlias = Literal['Name', 'Air Pollutants', 'Air Quality Category', 'Air Quality Index', 'Sunset Time', 'Sunrise Time', 'UV Index', 'Wind Direction', 'Wind Speed', 'Precipitation Chance', 'Precipitation Amount', 'Pressure', 'Humidity', 'Dewpoint', 'Visibility', 'Condition', 'Feels Like', 'Low', 'High', 'Temperature', 'Location', 'Date']
WeatherForecastTypesValue: TypeAlias = Literal['Daily', 'Hourly']
WebpageDetailValue: TypeAlias = Literal['Page Contents', 'Page Selection', 'Page URL', 'Name']
WifiDetailValue: TypeAlias = Literal['Network Name', 'BSSID', 'Wi-Fi Standard', 'RX Rate', 'TX Rate', 'RSSI', 'Noise', 'Channel Number', 'Hardware MAC Address']
WindowPositionValue: TypeAlias = Literal['Top Left', 'Top Center', 'Top Right', 'Middle Left', 'Center', 'Middle Right', 'Bottom Left', 'Bottom Center', 'Bottom Right', 'Coordinates']
WindowSizeValue: TypeAlias = Literal['Fit Screen', 'Top Half', 'Bottom Half', 'Left Half', 'Right Half', 'Top Left Quarter', 'Top Right Quarter', 'Bottom Left Quarter', 'Bottom Right Quarter', 'Dimensions']

# [Calendars] Add Calendar: Create a calendar with `name`.
def add_calendar(name: Input) -> Value[Any]: ...
# [Reminders] Add Quick Reminder
def add_quick_reminder() -> Value[Any]: ...
# [Books] Add to Books: Add `input` to books. `input` is expected to be a PDF or epub file.
def add_to_books(input: Input) -> Value[Any]: ...
# [GIFs] Add To GIF: Add a frame to a GIF.
def add_to_gif(image: Input, gif: Input, delay: Input | None = None, auto_size: BoolLike | Value[Any] | None = None, width: Input | None = None, height: Input | None = None) -> Value[Any]: ...
# Add to Music: Add music to library.
def add_to_music(songs: Input) -> Value[Any]: ...
# [Playlists] Add to Playlist
def add_to_playlist(playlist_name: Input, songs: Input) -> Value[Any]: ...
# [Weather] Add Location to List: Add a location to Weather app.
def add_weather_location(location: Input) -> Value[Any]: ...
# [Dates] Adjust Date: Adjust a date or get the start of a time period.
def adjust_date(date: Input, operation: DateAdjustOperationValue | Input, unit: Input | None = None) -> Value[Any]: ...
# [Writing Tools] Adjust Text Tone: Adjust the tone of the text using Apple Intelligence Writing Tools.
def adjust_text_tone(text: Input, tone: TextToneValue | Input) -> Text: ...
# [AirDrop] AirDrop: Prompt the user to AirDrop `input`.
def airdrop(input: Input) -> Value[Any]: ...
# [Notifications] Alert: Shows an alert with text and optional title and an OK button to proceed.
def alert(alert: Input, title: Input | None = None) -> Value[Any]: ...
# [Text Editing] Alternating Case: Capitalizes the text with alternating case.
def alternating_case(text: Input) -> Text: ...
# [Notes] Append Note: Append text to a note.
def append_note(note: Input, input: Input) -> Value[Any]: ...
# [Files & Folders] Append File: Append text to a file.
def append_to_file(file_path: Input, text: Input) -> Value[Any]: ...
# [Language Models] Ask Chat GPT: Ask Chat GPT using a prompt. Follow up will open a follow-up prompt to the model.
def ask_chat_gpt(prompt: Input, follow_up: BoolLike | Value[Any] | None = None, result_type: GenerativeResultTypeValue | Input | None = None) -> Value[Any]: ...
# [Language Models] Ask Private Cloud Compute LLM: Ask a private cloud compute LLM using a prompt. Follow up will open a follow-up prompt to the model.
def ask_cloud_llm(prompt: Input, follow_up: BoolLike | Value[Any] | None = None, result_type: GenerativeResultTypeValue | Input | None = None) -> Value[Any]: ...
# [Language Models] Ask On-Device LLM: Ask an On-Device LLM using a prompt. Follow up will open a follow-up prompt to the model.
def ask_device_llm(prompt: Input, follow_up: BoolLike | Value[Any] | None = None, result_type: GenerativeResultTypeValue | Input | None = None) -> Value[Any]: ...
# [Language Models] Ask LLM: Ask a specific LLM using a prompt. Follow up will open a follow-up prompt to the model.
def ask_llm(prompt: Input, model: LlmModelValue | Input | None = None, follow_up: BoolLike | Value[Any] | None = None, result_type: GenerativeResultTypeValue | Input | None = None) -> Value[Any]: ...
# Base 64 Decode: Base 64 decodes input.
def base64_decode(input: Input) -> Text: ...
# Base 64 Encode: Base 64 encodes input.
def base64_encode(encode_input: Input) -> Text: ...
# Calculate: Perform various calculation operations using one or two operands.
def calculate(operation: CalculationOperationValue | Input, operand_one: NumberLike | Value[Any], operand_two: NumberLike | Value[Any] | None = None) -> Number: ...
# [Phone] Call: Call a contact.
def call(contact: Input) -> Value[Any]: ...
# [Text Editing] Capitalize: Capitalizes the text with sentence case.
def capitalize(text: Input) -> Text: ...
# [Text Editing] Capitalize All: Capitalizes every word in the text.
def capitalize_all(text: Input) -> Text: ...
# [Rounding] Round Up: Always round a number up to a specified rounding place.
def ceil(number: NumberLike | Value[Any], round_to: RoundingValue | Input | None = None) -> Value[Any]: ...
# [Lists] Choose from List: Prompts the user to choose from a list.
def choose_from_list(list: Input, prompt: Input | None = None, select_multiple: BoolLike | Value[Any] | None = None, select_all: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Playback] Clear Up Next: Clear the queue.
def clear_up_next() -> Value[Any]: ...
# [Image Editing] Combine Images
def combine_images(images: Input, mode: ImageCombineModeValue | Input | None = None, spacing: NumberLike | Value[Any] | None = None) -> Value[Any]: ...
# Comment: Add an explicit comment.
def comment(text: Input) -> Value[Any]: ...
# [Notifications] Confirm: Shows an alert with text and optional title. It displays an OK button to proceed, and a cancel button that stops the Shortcut.
def confirm(alert: Input, title: Input | None = None) -> Value[Any]: ...
# [Server] Connect to Server: Connect to file server at `url`.
def connect_to_server(url: Input) -> Value[Any]: ...
# [Battery] Connected to Charger: Determines if the device is currently connected to a charger.
def connected_to_charger() -> Bool: ...
# [Output] Content Graph: Display input as a content graph.
def content_graph(input: Input) -> Value[Any]: ...
# [Image Editing] Convert Image: Convert image to another format, compression quality, and/or remove metadata.
def convert_image(image: Input, format: ConvertImageFormatsValue | Input, quality: NumberLike | Value[Any] | None = None, preserve_metadata: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Image Editing] Convert to JPEG: Convert image to a JPEG.
def convert_to_jpeg(image: Input, compression_quality: NumberLike | Value[Any] | None = None, preserve_metadata: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Convert to USDZ
def convert_to_usdz(file: Input) -> Value[Any]: ...
# [Text Editing] Correct Spelling: Corrects the spelling of the provided text.
def correct_spelling(text: Input) -> Text: ...
# Count: Returns a count of `type` of items in `input`.
def count(input: Input, type: CountTypeValue | Input | None = None) -> Number: ...
# Create Album
def create_album(name: Input, images: Input | None = None) -> Value[Any]: ...
# [Files & Folders] Create Folder: Create a folder.
def create_folder(path: Input) -> Value[Any]: ...
# [Image Editing] Crop Image
def crop_image(image: Input, width: Input | None = None, height: Input | None = None, position: CropImagePositionValue | Input | None = None, custom_position_x: Input | None = None, custom_position_y: Input | None = None) -> Value[Any]: ...
# [Dates] Current Date: Get the current date.
def current_date() -> Value[Any]: ...
# Current Location: Get current user location.
def current_location() -> Value[Any]: ...
# [Image Editing] Custom Image Mask: Mask an image with a custom image mask.
def custom_image_mask(image: Input, custom_mask_image: Input) -> Value[Any]: ...
# [Image Editing] Custom Image Overlay: Specify custom image overlay configuration.
def custom_image_overlay(image: Input, overlay_image: Input, width: Input | None = None, height: Input | None = None, rotation: Input | None = None, opacity: Input | None = None, position: CustomImageOverlayPositionValue | Input | None = None, custom_position_x: Input | None = None, custom_position_y: Input | None = None) -> Value[Any]: ...
# [Appearance] Set Appearance to Dark
def dark_mode() -> Value[Any]: ...
# [Dates] Date: Create a date value from `date`. Example: October 5, 2022.
def date(date: Input) -> Value[Any]: ...
# Define: Returns the definition of the word.
def define(word: Input) -> Text: ...
# [Files & Folders] Delete Files: Delete a file or multiple files.
def delete_files(input: Input, immediately: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Delete Photos
def delete_photos(photos: Input) -> Value[Any]: ...
# Detect Language: Detect the language of the text in `input`.
def detect_language(input: Input) -> Text: ...
# [System] Dismiss Siri: Dismisses Siri.
def dismiss_siri() -> Value[Any]: ...
# [Device] Display Sleep: Only puts the Mac display to sleep, device remains awake.
def display_sleep() -> Value[Any]: ...
# [Notifications] Turn Off Do Not Disturb
def dnd_off() -> Value[Any]: ...
# [Notifications] Turn On Do Not Disturb
def dnd_on() -> Value[Any]: ...
# [HTTP] Download URL: Download the contents of a URL.
def download_url(url: Input, headers: DictLike | Value[Any] | None = None) -> Value[Any]: ...
# [Calendars] Edit Event: Edit a detail of an event. Provide an event, a detail to modify, and a new value for that detail.
def edit_event(event: Input, detail: EditEventDetailValue | Input, new_value: Input) -> Value[Any]: ...
# [Audio] Encode Audio: Encode audio to a different format and/or speed.
def encode_audio(audio: Input, format: AudioFormatsValue | Input | None = None, speed: AudioSpeedsValue | Input | None = None) -> Value[Any]: ...
# [Video Editing] Encode Video: Encode a video to a different format, size and/or speed.
def encode_video(video: Input, size: EncodeVideoSizesValue | Input | None = None, speed: EncodeVideoSpeedsValue | Input | None = None, preserve_transparency: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [URLs] Expand URL: Get the expanded version of a URL. For instance, returns the full URL for a short URL, or the URL which a URL immediately redirects to, etc.
def expand_url(url: Input) -> Value[Any]: ...
# [Archives] Extract Archive: Extract files from the archive `file`.
def extract_archive(file: Input) -> Value[Any]: ...
# [Image Editing] Extract Image Text
def extract_image_text(image: Input) -> Text: ...
# [Phone] FaceTime Call: Starts a FaceTime audio or video call with the contact.
def facetime_call(contact: Input, type: FacetimeCallTypeValue | Input | None = None) -> Value[Any]: ...
# [HTTP] File Request: Send a `method` file request to `url` with `body` and optional `headers.
def file_request(url: Input, method: HttpMethodValue | Input | None = None, body: DictLike | Value[Any] | None = None, headers: DictLike | Value[Any] | None = None) -> Value[Any]: ...
# [Files & Folders] File Size: Returns the size of a file.
def file_size(file: Input, format: FileSizeFormatValue | Input) -> Value[Any]: ...
# Filter Contacts
def filter_contacts(contacts: Input, sort_by: ContactDetailValue | Input | None = None, sort_order: Input | None = None, limit: NumberLike | Value[Any] | None = None) -> Value[Any]: ...
# [Email & SMS Messaging] Find Conversation: Find SMS/iMessage conversation.
def find_conversation(search: Input) -> Value[Any]: ...
# [Email & SMS Messaging] Find Email: Find email.
def find_email(search: Input) -> Value[Any]: ...
# [Email & SMS Messaging] Find Message: Find SMS/iMessage message.
def find_message(search: Input) -> Value[Any]: ...
# [Image Editing] Flip Image
def flip_image(image: Input, direction: FlipImageDirectionValue | Input) -> Value[Any]: ...
# [Rounding] Round Down: Always round a number down to a specified rounding place.
def floor(number: NumberLike | Value[Any], round_to: RoundingValue | Input | None = None) -> Value[Any]: ...
# [HTTP] Form Request: Send a `method` request to `url` with `body` and optional `headers.
def form_request(url: Input, method: HttpMethodValue | Input | None = None, body: DictLike | Value[Any] | None = None, headers: DictLike | Value[Any] | None = None) -> Value[Any]: ...
# [Formatting] Format Date: Format a date using a standard or custom format.
def format_date(date: Input, date_format: DateFormatsValue | Input | None = None, custom_date_format: Input | None = None) -> Value[Any]: ...
# [Numbers] Format Number: Format number based on decimal place.
def format_number(number: NumberLike | Value[Any], decimal_places: NumberLike | Value[Any] | None = None) -> Number: ...
# [Formatting] Format Time: Format a time using a standard or custom format.
def format_time(time: Input, time_format: TimeFormatsValue | Input | None = None) -> Value[Any]: ...
# [Formatting] Format Timestamp: Format a timestamp using standard formats and/or a custom date format.
def format_timestamp(date: Input, date_format: DateFormatsValue | Input | None = None, time_format: TimeFormatsValue | Input | None = None, custom_date_format: Input | None = None) -> Value[Any]: ...
# [Writing Tools] Summarize Text Key Points: Generate a summary of key points of text using Apple Intelligence Writing Tools.
def generate_key_points(text: Input) -> Text: ...
# [Writing Tools] Make List From Text: Generate list from text  using Apple Intelligence Writing Tools.
def generate_list(text: Input) -> Text: ...
# [Writing Tools] Proofread Text: Generate a proofread version of text using Apple Intelligence Writing Tools.
def generate_proofread(text: Input) -> Text: ...
# [Writing Tools] Rewrite Text: Generate a rewritten version of text using Apple Intelligence Writing Tools.
def generate_rewrite(text: Input) -> Text: ...
# [Writing Tools] Summarize Text: Generate a summarized version of text using Apple Intelligence Writing Tools.
def generate_summary(text: Input) -> Text: ...
# [Writing Tools] Make Table From Text: Generate table from text using Apple Intelligence Writing Tools.
def generate_table(text: Input) -> Text: ...
# [Addresses] Get Addresses: Get addresses from `input`.
def get_addresses(input: Input) -> Value[Any]: ...
# [Alarms] Get Alarms: Returns all of the alarms on the device.
def get_alarms() -> Value[Any]: ...
# [Wallpaper] Get Wallpapers: Get device wallpapers.
def get_all_wallpapers() -> List[Any]: ...
# Get Apps: Get list of applications.
def get_apps() -> List[Any]: ...
# [Articles] Get Article: Get article from webpage.
def get_article(webpage: Input) -> Value[Any]: ...
# [Articles] Get Article Detail: Get a detail about an article.
def get_article_detail(article: Input, detail: Input) -> Value[Any]: ...
# [Battery] Get Battery Level: Get the current level of charge of the device battery.
def get_battery_level() -> Value[Any]: ...
# [Wireless] Get Cellular Detail: Get a detail of the current Cellular network.
def get_cellular_detail(detail: CellularDetailValue | Input) -> Value[Any]: ...
# [Clipboard] Get Clipboard: Get the contents of the clipboard.
def get_clipboard() -> Value[Any]: ...
# Get Detail of Contact: Get a detail about a contact.
def get_contact_detail(contact: Input, detail: ContactDetailValue | Input) -> Value[Any]: ...
# Get Contacts: Get contacts from input.
def get_contacts(input: Input) -> List[Any]: ...
# Get Current Location
def get_current_location() -> Value[Any]: ...
# Get Current Song: Gets the currently playing song.
def get_current_song() -> Value[Any]: ...
# [Safari] Get Current URL: Get current URL in Safari.
def get_current_url() -> Value[Any]: ...
# [Weather] Get Current Weather: Get the current weather for a location.
def get_current_weather(location: Input | None = None) -> Value[Any]: ...
# [Dates] Get Dates: Get dates from input.
def get_dates(input: Input) -> List[Any]: ...
# Get Device Detail: Get a detail about current device.
def get_device_detail(detail: DeviceDetailValue | Input) -> Value[Any]: ...
# [Screen Time] Get Website & App Activity
def get_device_usage(usage_type: DeviceUsageTypeValue | Input | None = None, device: Input | None = None, during: UsageDurationValue | Input | None = None, start_time: Input | None = None, end_time: Input | None = None) -> Value[Any]: ...
# [Dictionaries] Get Dictionary: Get the dictionary from `input`.
def get_dictionary(input: Input) -> Dictionary: ...
# [Email] Get Emails: Get emails from input.
def get_emails(input: Input) -> List[Any]: ...
# Get Name of Emoji: Detects emoji in the text and returns its name.
def get_emoji_name(emoji: Input) -> Text: ...
# [Calendars] Get Event Detail: Get a detail of an event.
def get_event_detail(event: Input, detail: EventDetailValue | Input) -> Value[Any]: ...
# [IP Address] Get External IP: Get the users external IP address.
def get_external_ip(type: IpTypesValue | Input | None = None) -> Text: ...
# [Files & Folders] Get File: Get file from a path in the Shortcuts folder.
def get_file(path: Input, error_if_not_found: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Files & Folders] Get File Detail: Get a detail about a file.
def get_file_detail(file: Input, detail: FileDetailValue | Input) -> Value[Any]: ...
# [Files & Folders] Get File Link: Get a link for the provided file.
def get_file_link(file: Input) -> Value[Any]: ...
# [Lists] Get First Item: Get first item in a list.
def get_first_item(list: Input) -> Value[Any]: ...
# [Notifications] Get Focus Mode: Get the current Focus Mode.
def get_focus_mode() -> Value[Any]: ...
# [Giphy] Get GIFs from Giphy: Gets a number of GIFs from Giphy for a search query.
def get_gifs(query: Input, gifs: NumberLike | Value[Any] | None = None) -> Value[Any]: ...
# [Maps] Get Halfway Point: Get the halfway point between two locations.
def get_halfway_point(first_location: Input, second_location: Input) -> Value[Any]: ...
# [Dates] Get Holiday Date: Get the date of a holiday, optionally specifically for a few past or future years.
def get_holiday_date(holiday: HolidayValue | Input, occurrence_mode: EventOccurrenceModeValue | Input | None = None, for_year: HolidayYearValue | Input | None = None) -> Text: ...
# [Image Editing] Get Image Detail: Get a detail about an image.
def get_image_detail(image: Input, detail: ImageDetailValue | Input) -> Value[Any]: ...
# [GIFs] Get Image Frames: Get frames from a GIF.
def get_image_frames(image: Input) -> Value[Any]: ...
# [Image Editing] Get Images: Detect images in input
def get_images(input: Input) -> List[Any]: ...
# [Dictionaries] Get Keys from Dictionary: Get only the keys from the `dictionary`.
def get_keys(dictionary: DictLike | Value[Any]) -> List[Any]: ...
# Get Last Import
def get_last_import() -> Value[Any]: ...
# [Lists] Get Last Item: Get the last item in a list.
def get_last_item(list: Input) -> Value[Any]: ...
# Get Latest Bursts
def get_latest_bursts(count: NumberLike | Value[Any]) -> Value[Any]: ...
# Get Latest Live Photos
def get_latest_live_photos(count: NumberLike | Value[Any]) -> Value[Any]: ...
# Get Latest Photos
def get_latest_photos(count: NumberLike | Value[Any], include_screenshots: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Get Latest Screenshots
def get_latest_screenshots(count: NumberLike | Value[Any]) -> Value[Any]: ...
# Get Latest Videos
def get_latest_videos(count: NumberLike | Value[Any]) -> Value[Any]: ...
# [Lists] Get List Item: Get item from `list` at `index`. Keep in mind Shortcuts starts counting indexes at 1.
def get_list_item(list: Input, index: NumberLike | Value[Any]) -> Value[Any]: ...
# [Lists] Get List Items: Get items from a `list` between two indexes. Keep in mind Shortcuts starts counting indexes at 1.
def get_list_items(list: Input, start: NumberLike | Value[Any], end: NumberLike | Value[Any]) -> List[Any]: ...
# [IP Address] Get Local IP: Get the users local IP address.
def get_local_ip(type: IpTypesValue | Input | None = None) -> Text: ...
# Get Location Detail: Get a detail about a location.
def get_location_detail(location: Input, detail: LocationDetailValue | Input) -> Value[Any]: ...
# [Maps] Get Maps Link: Get a link for a location.
def get_maps_link(location: Input) -> Value[Any]: ...
# [Regular Expressions] Get Match Group: Get match group at `index` in `matches`.
def get_match_group(matches: Input, index: NumberLike | Value[Any]) -> Value[Any]: ...
# [Regular Expressions] Get Match Groups: Get all groups in `matches`.
def get_match_groups(matches: Input) -> Value[Any]: ...
# Get Music Detail: Get a detail about a song.
def get_music_detail(music: Input, detail: MusicDetailValue | Input) -> Value[Any]: ...
# [Items] Get Name: Get the name of an item.
def get_name(item: Input) -> Value[Any]: ...
# [Numbers] Get Numbers: Get numbers from input.
def get_numbers(input: Input) -> Number: ...
# Get Object of Class: Get the object of `class` from a variable.
def get_object_of_class(class_: Input, from_: Input) -> Value[Any]: ...
# Get On-Screen Content: Get the content currently on-screen.
def get_on_screen_content() -> Value[Any]: ...
# Get Orientation: Get the current orientation of the device.
def get_orientation() -> Text: ...
# [Files & Folders] Get Parent Directory: Get the parent directory of the input directory.
def get_parent_directory(input: Input) -> Value[Any]: ...
# [Phone] Get Phone Numbers: Get phone numbers from input.
def get_phone_numbers(input: Input) -> List[Any]: ...
# [Playlists] Get Playlist: Gets songs from a playlist
def get_playlist_songs(playlist_name: Input) -> List[Any]: ...
# [Podcasts] Get Podcast Detail
def get_podcast_detail(podcast: Input, detail: PodcastDetailValue | Input) -> Value[Any]: ...
# [Podcasts] Get Podcasts: Get users podcasts.
def get_podcasts() -> Value[Any]: ...
# [Lists] Get Random Item: Get random item from list.
def get_random_item(list: Input) -> Value[Any]: ...
# [Rich Text] Make Rich Text from HTML
def get_rich_text_from_html(html: Input) -> Text: ...
# [Rich Text] Get Rich Text from Markdown
def get_rich_text_from_markdown(markdown: Input) -> Text: ...
# [RSS] Get RSS: Get RSS feed contents at URL. Limited by number of items.
def get_rss(items: NumberLike | Value[Any], url: Input) -> Value[Any]: ...
# [RSS] Get RSS Feeds: Get feeds from multiple URLs.
def get_rss_feeds(urls: Input) -> Value[Any]: ...
# [Files & Folders] Get Selected
def get_selected_files() -> Value[Any]: ...
# [Shazam] Get Shazam Detail: Get a detail about a Shazam result.
def get_shazam_detail(input: Input, detail: ShazamDetailValue | Input) -> Value[Any]: ...
# Get Shortcut Detail: Get a detail about a Shortcut.
def get_shortcut_detail(shortcut: Input, detail: ShortcutDetailValue | Input) -> Value[Any]: ...
# Get Shortcuts: Get all of the Shortcuts on the device.
def get_shortcuts() -> List[Any]: ...
# Get Text: Get text from input.
def get_text(input: Input) -> Text: ...
# Get Text from Image
def get_text_from_image(image: Input) -> Text: ...
# [URLs] Get URLs: Get URLs from `input`.
def get_ur_ls(input: Input) -> List[Any]: ...
# [URLs] Get URL Detail: Get a detail about a URL.
def get_url_detail(url: Input, detail: UrlDetailValue | Input) -> Value[Any]: ...
# [URLs] Get URL Headers: Get the headers from a URL.
def get_url_headers(url: Input) -> Value[Any]: ...
# [Dictionaries] Get Value from Dictionary: For constants only, otherwise `dictionary['key']` syntax should be used.
def get_value(dictionary: DictLike | Value[Any], key: Input) -> Value[Any]: ...
# [Dictionaries] Get Values from Dictionary: Get only the values from the `dictionary`.
def get_values(dictionary: DictLike | Value[Any]) -> List[Any]: ...
# [Wallpaper] Get Wallpaper: Get current device wallpaper.
def get_wallpaper() -> Value[Any]: ...
# [Weather] Get Weather Detail: Get a detail about a weather forecast.
def get_weather_detail(weather: Input, detail: WeatherDetailValue | Input) -> Value[Any]: ...
# [Weather] Get Weather Forecast: Get various types of weather forecast for a location.
def get_weather_forecast(type: WeatherForecastTypesValue | Input | None = None, location: Input | None = None) -> Value[Any]: ...
# [Safari] Get Webpage Detail: Get a detail about a provided webpage.
def get_web_page_detail(webpage: Input, detail: WebpageDetailValue | Input) -> Value[Any]: ...
# [Safari] Get Webpage Contents: Get contents of Webpage from Safari.
def get_webpage_contents(url: Input) -> Value[Any]: ...
# [Wireless] Get WiFi Detail: Get a detail of the current WiFi network.
def get_wifi_detail(detail: WifiDetailValue | Input) -> Value[Any]: ...
# Hash: Generate a hash of type using input.
def hash(input: Input, type: HashTypeValue | Input | None = None) -> Text: ...
# [Battery] Is Charging: Determines if the device is currently charging.
def is_charging() -> Bool: ...
# [IP Address] Is Online: Determine if the user is online. Alias for get Get External IP.
def is_online() -> Value[Any]: ...
# [HTTP] JSON Request: Send a `method` JSON request to `url` with `body` and optional `headers.
def json_request(url: Input, method: HttpMethodValue | Input | None = None, body: DictLike | Value[Any] | None = None, headers: DictLike | Value[Any] | None = None) -> Value[Any]: ...
# [Appearance] Set Appearance to Light
def light_mode() -> Value[Any]: ...
# Dictation: Transcribes user recorded audio to text, optionally in another language.
def listen(stop_listening: StopListeningTriggerValue | Input | None = None, language: Input | None = None) -> Text: ...
# Location: Create a location value.
def location(location: Input) -> Value[Any]: ...
# Lock Screen: Lock the device screen.
def lock_screen() -> Value[Any]: ...
# [Text Editing] Lowercase: Transforms the text to all lowercase.
def lowercase(text: Input) -> Text: ...
# [Magnifier] Describe This
def magnifier_describe() -> Value[Any]: ...
# [Magnifier] Start Point & Speak
def magnifier_point_and_speak() -> Value[Any]: ...
# [Magnifier] Open Reader
def magnifier_reader() -> Value[Any]: ...
# [Archives] Make Archive: Create an archive of `files` named `name` in `format`.
def make_archive(files: Input, format: ArchiveFormatValue | Input | None = None, name: Input | None = None) -> Value[Any]: ...
# Make Disk Image: Create a new disk image.
def make_disk_image(name: Input, contents: Input, encrypt: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [GIFs] Make GIF
def make_gif(input: Input, delay: Input | None = None, loops: NumberLike | Value[Any] | None = None, width: Input | None = None, height: Input | None = None) -> Value[Any]: ...
# [Rich Text] Make HTML: Make HTML from Rich Text.
def make_html(input: Input, make_full_document: BoolLike | Value[Any] | None = None) -> Text: ...
# Make Image from PDF Page: Returns an image of the provided PDF.
def make_image_from_pdf_page(pdf: Input, color_space: ColorSpaceValue | Input | None = None, page_resolution: Input | None = None) -> Value[Any]: ...
# [Image Editing] Make Image from Rich Text
def make_image_from_rich_text(pdf: Input, width: Input, height: Input) -> Value[Any]: ...
# [Rich Text] Make Markdown: Make Markdown from Rich Text.
def make_markdown(rich_text: Input) -> Text: ...
# Make PDF: Make a PDF file using the provided input.
def make_pdf(input: Input, include_margin: BoolLike | Value[Any] | None = None, merge_behavior: PdfMergeBehaviorsValue | Input | None = None) -> Value[Any]: ...
# [QR Codes] Make QR Code
def make_qr_code(input: Input, error_correction: QrCodeErrorCorrectionValue | Input | None = None, foreground_color: Input | None = None, background_color: Input | None = None) -> Value[Any]: ...
# Make Shortcut: Create a shortcut.
def make_shortcut(name: Input, open: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Make Sized Disk Image: Create a new disk image of a specific size.
def make_sized_disk_image(name: Input, contents: Input, disk_size: Input | None = None, encrypt: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Make Spoken Audio: Creates custom spoken audio from text with controls for rate and pitch.
def make_spoken_audio(text: Input, rate: NumberLike | Value[Any] | None = None, pitch: NumberLike | Value[Any] | None = None) -> Value[Any]: ...
# [GIFs] Make Video From GIF
def make_video_from_gif(gif: Input, loops: NumberLike | Value[Any] | None = None) -> Value[Any]: ...
# [Editing] Markup: Opens document in a markup editor.
def markup(document: Input) -> Value[Any]: ...
# [Image Editing] Mask Image: Mask an image with another image.
def mask_image(image: Input, type: MaskImageTypeValue | Input, radius: Input | None = None) -> Value[Any]: ...
# [Regular Expressions] Match Text: Use regular expressions to match text.
def match_text(regex_pattern: Input, text: Input, case_sensitive: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Windows] Move Window: Move a window to a defined position.
def move_window(window: Input, position: WindowPositionValue | Input, bring_to_front: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Output] Must Output: Stop and output `output`. Respond with response if there is nowhere to output.
def must_output(output: Input, response: Input) -> Value[Any]: ...
# Nothing: Clear the current output.
def nothing() -> Value[Any]: ...
# Number: Create a number value.
def number(number: Input) -> Number: ...
# [Files & Folders] Open File: Open a file.
def open_file(file: Input, ask_when_run: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Maps] Open in Maps: Open a location in maps.
def open_in_maps(location: Input) -> Value[Any]: ...
# [Notes] Open Note: Open note in the Notes app.
def open_note(note: Input) -> Value[Any]: ...
# [Reminders] Open Reminders List
def open_reminders_list(list: Input) -> Value[Any]: ...
# [URLs] Open URL: Open URL in default browser.
def open_url(url: Input) -> Value[Any]: ...
# [URLs] Open X-Callback URL
def open_x_callback_url(url: Input) -> Value[Any]: ...
# Optimize PDF: Returns a compressed version of the PDF.
def optimize_pdf(pdf_file: Input) -> Value[Any]: ...
# [Output] Stop and Output: Stop and output `output`. Do nothing if there is nowhere to output.
def output(output: Input) -> Value[Any]: ...
# [Output] Output or Copy to Clipboard: Stop and output `output`. Copy to the clipboard if there is nowhere to output.
def output_or_clipboard(output: Input) -> Value[Any]: ...
# [Image Editing] Overlay Image: Overlay an image on top of another image.
def overlay_image(image: Input, overlay_image: Input) -> Value[Any]: ...
# [Playback] Pause: Press pause.
def pause() -> Value[Any]: ...
# [Playback] Play: Press play.
def play() -> Value[Any]: ...
# [Playback] Play Next: Add music to the end of the queue.
def play_later(music: Input) -> Value[Any]: ...
# Play Music: Set music to play with modes for shuffle and repeat.
def play_music(music: Input, shuffle: ShuffleModeValue | Input | None = None, repeat: RepeatModeValue | Input | None = None) -> Value[Any]: ...
# [Playback] Play Next: Add music to play next in the queue.
def play_next(music: Input) -> Value[Any]: ...
# [Podcasts] Play Podcast
def play_podcast(podcast: Input) -> Value[Any]: ...
# [Audio] Play Audio: Play a sound.
def play_sound(input: Input) -> Value[Any]: ...
# [Files & Folders] Prepend File: Prepend text to a file.
def prepend_to_file(file_path: Input, text: Input) -> Value[Any]: ...
# [Printing] Print: Print input to a printer.
def print(input: Input) -> Value[Any]: ...
# [Output] Quick Look: Preview `input` in Quick Look.
def quicklook(input: Input) -> Value[Any]: ...
# [Numbers] Random Number: Returns a random number between `min` and `max`.
def random_number(min: NumberLike | Value[Any], max: NumberLike | Value[Any]) -> Number: ...
# Reboot: Power off the device, then power it on again.
def reboot() -> Value[Any]: ...
# [Audio] Record Audio: Prompt the user to record audio.
def record_audio(quality: AudioQualityValue | Input | None = None, start: AudioStartValue | Input | None = None) -> Value[Any]: ...
# [Image Editing] Remove Image Background
def remove_background(image: Input, crop: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Calendars] Remove Events: Remove an event.
def remove_events(events: Input, include_future_events: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Remove Photo from Album
def remove_from_album(photo: Input, album: Input) -> Value[Any]: ...
# [Reminders] Remove Reminders
def remove_reminders(reminders: Input) -> Value[Any]: ...
# [Weather] Remove Location from List: Remove a location from the Weather app.
def remove_weather_location(location: Input) -> Value[Any]: ...
# [Files & Folders] Rename File
def rename(file: Input, new_name: Input) -> Value[Any]: ...
# Rename Album
def rename_album(album: Input, new_title: Input) -> Value[Any]: ...
# [Text Editing] Replace Text: Replace `find` in `subject`, optionally using a regular expression or case insensitive search.
def replace_text(find: Input, replacement: Input, subject: Input, case_sensitive: BoolLike | Value[Any] | None = None, reg_exp: BoolLike | Value[Any] | None = None) -> Text: ...
# [Image Editing] Resize Image By Longest Edge
def resize_image_by_longest_edge(image: Input, length: Input) -> Value[Any]: ...
# [Image Editing] Resize Image By Percent
def resize_image_by_percent(image: Input, percentage: Input) -> Value[Any]: ...
# [Windows] Resize Window: Resize a window to defined size.
def resize_window(window: Input, configuration: WindowSizeValue | Input) -> Value[Any]: ...
# [Files & Folders] Reveal in Finder
def reveal(files: Input) -> Value[Any]: ...
# [Image Editing] Rotate Media: Rotate an image or a video
def rotate_media(media: Input, degrees: Input) -> Value[Any]: ...
# [Rounding] Round: Rounds number to specified rounding place.
def round(number: NumberLike | Value[Any], round_to: RoundingValue | Input | None = None) -> Value[Any]: ...
# Run Shortcut: Run Shortcut with name `shortcutName`, providing it with `input`.
def run(shortcut_name: Input, input: Input) -> Value[Any]: ...
# [Scripts] Run Apple Script
def run_apple_script(input: Input, script: Input) -> Value[Any]: ...
# [Safari] Run JavaScript on Webpage: Run some custom JavaScript on the current webpage in Safari.
def run_java_script_on_webpage(javascript: Input) -> Value[Any]: ...
# [Scripts] Run JavaScript for Automation
def run_js_automation(input: Input, script: Input) -> Value[Any]: ...
# [Scripts] Run Shell Script
def run_shell_script(script: Input, input: Input, shell: Input | None = None, input_mode: Input | None = None) -> Value[Any]: ...
# [Server] Run SSH Script: Run an SSH script using connection details.
def run_ssh_script(script: Input, input: Input, host: Input, port: Input, user: Input, auth_type: SshScriptAuthTypeValue | Input, password: Input) -> Value[Any]: ...
# [Files & Folders] Save File Prompt: Prompt the user to choose a location to save the file.
def save_file_prompt(file: Input, overwrite: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Files & Folders] Save File: Save contents to a file at the specified path.
def save_file_to_path(path: Input, content: Input, overwrite: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Save Photo to Album
def save_photo(image: Input, album: Input | None = None) -> Value[Any]: ...
# Save File to Dropbox: Save a file to Dropbox. Requires user to setup Dropbox account in Shortcuts app.
def save_to_dropbox(file: Input, path: Input, overwrite: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Save File to Dropbox Prompt: Prompt to save a file to Dropbox. Requires user to setup Dropbox account in Shortcuts app.
def save_to_dropbox_prompt(file: Input, overwrite: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Search] Search/Spotlight: Get results from search on iOS or iPadOS, and Spotlight on macOS.
def search(query: Input, limit: NumberLike | Value[Any] | None = None, result_type: ArrayLike | Value[Any] | None = None) -> List[Any]: ...
# Search App Store
def search_app_store(query: Input) -> Value[Any]: ...
# [Giphy] Search Giphy: Gets GIFs from Giphy for a search query.
def search_giphy(query: Input) -> Value[Any]: ...
# [Passwords] Search Passwords: Searches passwords in the Passwords app.
def search_passwords(query: Input) -> Value[Any]: ...
# Search Photos
def search_photos(criteria: Input) -> List[Any]: ...
# [Podcasts] Search Podcasts
def search_podcasts(query: Input) -> Value[Any]: ...
# Search Shortcuts: Search the users Shortcuts.
def search_shortcuts(query: Input) -> Value[Any]: ...
# [Voice Memos] Search Voice Memos
def search_voice_memos(search: Input) -> List[Any]: ...
# [Safari] Search Web: Search the web using a provided search engine and query.
def search_web(engine: SearchEngineValue | Input, query: Input) -> Value[Any]: ...
# [Playback] Seek: Seek the currently playing media.
def seek(time_interval: Input | None = None, behavior: SeekBehaviorValue | Input | None = None) -> Value[Any]: ...
# Select Contact: Prompt the user to select a contact or multiple contacts. Returns selected contact.
def select_contact(multiple: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Email] Select Email Address: Prompt the user to select an email address from their contacts.
def select_email_address() -> Value[Any]: ...
# [Files & Folders] Select File: Prompt the user to select one or optionally multiple files.
def select_file(select_multiple: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Files & Folders] Select Folder: Prompt the user to select one or optionally multiple folders.
def select_folder(select_multiple: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Select Music: Prompt the user to select music.
def select_music(select_multiple: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Phone] Select Phone Number: Prompt the user to select a phone number from their contacts.
def select_phone_number() -> Value[Any]: ...
# Select Photos: Prompt the user to select from their photo library.
def select_photos(select_multiple: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Email & SMS Messaging] Send Email: Send an email to a contact.
def send_email(contact: Input, from_: Input, subject: Input, body: Input, prompt: BoolLike | Value[Any] | None = None, draft: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Email & SMS Messaging] Send Message: Send an SMS/iMessage to a contact.
def send_message(contact: Input, message: Input, prompt: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [AirDrop] Set AirDrop Receiving: Set the AirDrop receiving setting.
def set_airdrop_receiving(state: AirdropReceivingStatesValue | Input | None = None) -> Value[Any]: ...
# Set Background Sound: Set the background sound that plays.
def set_background_sound(sound: BackgroundSoundValue | Input | None = None) -> Value[Any]: ...
# Set Background Sound Volume
def set_background_sounds_volume(volume: NumberLike | Value[Any]) -> Value[Any]: ...
# [Device] Set Brightness
def set_brightness(brightness: NumberLike | Value[Any]) -> Value[Any]: ...
# [Clipboard] Set Clipboard: Set the contents of the clipboard.
def set_clipboard(value: Input, local: BoolLike | Value[Any] | None = None, expire: Input | None = None) -> Value[Any]: ...
# [Metadata] Set Media Metadata
def set_metadata(media: Input, artwork: Input | None = None, title: Input | None = None, artist: Input | None = None, album: Input | None = None, genre: Input | None = None, year: Input | None = None) -> Value[Any]: ...
# [Items] Set Name: Set the name of an item.
def set_name(item: Input, name: Input, include_file_extension: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Hearing] Set Sound Recognition
def set_sound_recognition(operation: SoundRecognitionOperationsValue | Input | None = None) -> Value[Any]: ...
# [Vision] Set Text Size: Sets the system text size.
def set_text_size(size: TextSizesValue | Input) -> Value[Any]: ...
# [Dictionaries] Set Value in Dictionary: Set the value of `key` to `value` in `dictionary`.
def set_value(dictionary: Input, key: Input, value: Input) -> Dictionary: ...
# [Device] Set Volume
def set_volume(volume: NumberLike | Value[Any]) -> Value[Any]: ...
# [Wallpaper] Set Wallpaper: Sets the device wallpaper to `input`.
def set_wallpaper(input: Input) -> Value[Any]: ...
# Share: Prompt the user to share `input`.
def share(input: Input) -> Value[Any]: ...
# [Output] Show Result: Show `input`.
def show(input: Input) -> Value[Any]: ...
# [Calendars] Open Event in Calendar: Show `event` in the calendar app.
def show_in_calendar(event: Input) -> Value[Any]: ...
# Show In iTunes
def show_ini_tunes(product: Input) -> Value[Any]: ...
# [Notifications] Show Notification: Shows a custom notification message.
def show_notification(body: Input, title: Input | None = None, play_sound: BoolLike | Value[Any] | None = None, attachment: Input | None = None) -> Value[Any]: ...
# [Notes] Show Quick Note: Show quick note.
def show_quick_note() -> Value[Any]: ...
# [Safari] Show Webpage: Show webpage using Safari.
def show_webpage(url: Input, use_reader: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Shut Down: Power off the device.
def shutdown() -> Value[Any]: ...
# [Playback] Skip Back: Go to the previous song.
def skip_back() -> Value[Any]: ...
# [Playback] Skip Forward: Go to the next song.
def skip_fwd() -> Value[Any]: ...
# [Device] Sleep: Puts the Mac to sleep.
def sleep() -> Value[Any]: ...
# Speak: Speaks the provided text, optionally in another language.
def speak(prompt: Input, wait_until_finished: BoolLike | Value[Any] | None = None, language: Input | None = None) -> Value[Any]: ...
# Split PDF: Splits a PDF into pages.
def split_pdf(pdf: Input) -> List[Any]: ...
# [Device] Start Screensaver
def start_screensaver() -> Value[Any]: ...
# [Shazam] Start Shazam: Prompt the user to play music for Shazam to recognize. Returns Shazam result.
def start_shazam(show: BoolLike | Value[Any] | None = None, show_error: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Timers] Start Timer: Creates a new timer.
def start_timer(duration: Input | None = None) -> Value[Any]: ...
# Statistic: Perform a statistical operation on `input`.
def statistic(operation: StatisticOperationsValue | Input, input: Input) -> Value[Any]: ...
# Stop Shortcut: Stops the shortcut.
def stop() -> Value[Any]: ...
# [Addresses] Street Address: Create a location value with an address.
def street_address(address_line2: Input, wf_address_line2: Input, city: Input, state: Input, country: Input, zip_code: NumberLike | Value[Any]) -> Value[Any]: ...
# [Image Editing] Strip Image Metadata
def strip_image_metadata(image: Input) -> Value[Any]: ...
# [Metadata] Strip Media Metadata
def strip_media_metadata(media: Input) -> Value[Any]: ...
# Take Interactive Screenshot
def take_interactive_screenshot(selection: ScreenshotSelectionValue | Input | None = None) -> Value[Any]: ...
# [Camera] Take Photo: Prompt the user to take one or more photos.
def take_photo(count: NumberLike | Value[Any] | None = None, show_preview: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# Take Screenshot
def take_screenshot(main_monitor_only: BoolLike | Value[Any] | None = None) -> Value[Any]: ...
# [Camera] Take Photo: Prompt the user to start recording a video.
def take_video(camera: CameraOrientationValue | Input | None = None, quality: VideoQualityValue | Input | None = None, recording_start: RecordingStartValue | Input | None = None) -> Value[Any]: ...
def text(text: Input) -> Text: ...
# [Text Editing] Title Case: Capitalizes the text with Title Case.
def title_case(text: Input) -> Text: ...
# [Notifications] Toggle Do Not Disturb
def toggle_dnd() -> Value[Any]: ...
# [Playback] Toggle Play/Pause
def toggle_play_pause() -> Value[Any]: ...
# Transcribe Audio: Transcribes text from the provided audio.
def transcribe_text(audio: Input) -> Text: ...
# Translate: Translate text.
def translate(text: Input, to: Input, from_: Input | None = None) -> Text: ...
# [Video Editing] Trim Video: Prompts the user to trim the video.
def trim_video(video: Input) -> Value[Any]: ...
# [Text Editing] Trim Whitespace: Trim any whitespace from the start and end of `text`.
def trim_whitespace(text: Input) -> Text: ...
# Get Type: Get the type of input.
def type_of(input: Input) -> Text: ...
# [Text Editing] Uppercase: Transforms the text to all uppercase.
def uppercase(text: Input) -> Text: ...
# [URLs] URL Decode: Decode text from URL encoding.
def url_decode(input: Input) -> Text: ...
# [URLs] URL Encode: Encode text for a URL.
def url_encode(input: Input) -> Text: ...
# Vibrate Device: Vibrate the device. Only applies to Apple devices with the haptic engine.
def vibrate() -> Value[Any]: ...
# [Control Flow] Wait: Wait a specified number of seconds.
def wait(seconds: NumberLike | Value[Any]) -> Value[Any]: ...
# [Control Flow] Wait to Return: Wait for the user to return to Shortcuts.
def wait_to_return() -> Value[Any]: ...
